#!/usr/bin/env python3
"""Generate project-compatible SMPL-X assets from SHAPY body betas."""

from __future__ import annotations

import argparse
import json
import pickle
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np
import torch

from body_optimizer import refine_betas
from motion_catalog import (
    DEFAULT_ACTION_ID,
    action_by_id,
    resolve_action_asset,
)
from shapy_adapter import predict_betas


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--request", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--shapy-data-root", required=True, type=Path)
    parser.add_argument("--debug-betas", type=Path)
    parser.add_argument(
        "--device",
        default="auto",
        help="Torch device for SMPL-X mesh generation; auto prefers CUDA.",
    )
    return parser.parse_args()


def write_obj(path: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# SMPL-X body generated by AI Garment Pattern & 3D Simulation\n")
        for vertex in vertices:
            stream.write(f"v {vertex[0]:.9f} {vertex[1]:.9f} {vertex[2]:.9f}\n")
        for face in faces:
            stream.write(f"f {face[0] + 1} {face[1] + 1} {face[2] + 1}\n")


def save_motion(
    template_path: Path,
    output_path: Path,
    *,
    betas: np.ndarray,
    gender: str,
) -> None:
    template = np.load(template_path, allow_pickle=True)
    payload = {
        key: template[key]
        for key in template.files
        if key not in {"betas", "gender", "A_smplx"}
    }
    payload["betas"] = betas.astype(np.float32)
    payload["gender"] = np.asarray(gender)
    np.savez_compressed(output_path, **payload)


def load_debug_betas(path: Path) -> np.ndarray:
    payload = json.loads(path.read_text(encoding="utf-8"))
    values = payload["betas"] if isinstance(payload, dict) else payload
    return np.asarray(values, dtype=np.float32).reshape(-1)


def main() -> None:
    args = parse_args()
    if args.device == "auto":
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)
    if device.type == "cuda" and not torch.cuda.is_available():
        raise RuntimeError(f"requested {device}, but PyTorch CUDA is unavailable")
    request = json.loads(args.request.read_text(encoding="utf-8"))
    gender = str(request["gender"]).lower()
    if gender not in {"male", "female", "neutral"}:
        raise ValueError("gender must be male, female, or neutral")

    if args.debug_betas:
        betas10 = load_debug_betas(args.debug_betas)
        method: dict[str, Any] = {
            "method": "debug_supplied_betas",
            "trained_here": False,
        }
    else:
        betas10, method = predict_betas(
            request,
            data_root=args.shapy_data_root,
        )
    if not 1 <= len(betas10) <= 300:
        raise ValueError("body shape must contain between 1 and 300 betas")

    dynamic_root = args.project_root / "dynamic3d"
    contourcraft_root = dynamic_root / "src" / "ContourCraft-CG"
    sys.path.insert(0, str(contourcraft_root))
    from runners.smplx.body_models import SMPLXLayer

    data_root = dynamic_root / "assets" / "ccraft_data"
    model_path = (
        data_root
        / "aux_data"
        / "body_models"
        / "smplx"
        / f"SMPLX_{gender.upper()}.pkl"
    )
    registration_template = data_root / "rest_pose" / "registered_params.pkl"
    action_id = str(request.get("action_id", DEFAULT_ACTION_ID))
    action = action_by_id(args.project_root, action_id)
    motion_template = resolve_action_asset(args.project_root, action)
    for required in (model_path, registration_template):
        if not required.is_file():
            raise FileNotFoundError(required)
    if motion_template is not None and not motion_template.is_file():
        raise FileNotFoundError(
            f"selected action is not installed: {action_id}: {motion_template}"
        )

    with registration_template.open("rb") as stream:
        template = pickle.load(stream)
    pose = np.asarray(template["pred_pose"], dtype=np.float32).reshape(1, 55, 3)
    transl = np.asarray(template["pred_transl"], dtype=np.float32).reshape(1, 3)

    layer = SMPLXLayer(
        str(model_path),
        ext="pkl",
        num_betas=300,
    ).to(device)
    initial_betas10 = betas10.astype(np.float32).copy()
    body_shape = initial_betas10
    if (
        not args.debug_betas
        and bool(request.get("optimize_measurements", True))
    ):
        body_shape, optimization = refine_betas(
            initial_betas10,
            request,
            layer=layer,
            measurement_root=(
                args.shapy_data_root
                / "utility_files"
                / "measurements"
            ),
        )
        method["measurement_refinement"] = optimization
    else:
        method["measurement_refinement"] = {
            "enabled": False,
            "reason": (
                "debug betas"
                if args.debug_betas
                else "disabled by request"
            ),
        }

    betas = np.zeros(300, dtype=np.float32)
    betas[: len(body_shape)] = body_shape
    with torch.inference_mode():
        output = layer.forward_simple(
            betas=torch.from_numpy(betas[None]).to(device),
            full_pose=torch.from_numpy(pose).to(device),
            transl=torch.from_numpy(transl).to(device),
            pose2rot=True,
        )
    vertices = output.vertices.detach().cpu().numpy().astype(np.float32)
    joints = output.joints.detach().cpu().numpy().astype(np.float32)
    faces = layer.faces_tensor.detach().cpu().numpy().astype(np.int64)
    if vertices.shape != (1, 10475, 3) or joints.shape != (1, 55, 3):
        raise ValueError(
            f"unexpected SMPL-X output: vertices={vertices.shape}, joints={joints.shape}"
        )

    args.output_dir.mkdir(parents=True, exist_ok=False)
    registration = {
        "pred_shape": betas[None],
        "pred_pose": pose.reshape(1, 165),
        "pred_transl": transl,
        "joints": joints,
        "smplx_vertices": vertices,
    }
    with (args.output_dir / "registered_params.pkl").open("wb") as stream:
        pickle.dump(registration, stream, protocol=4)
    write_obj(args.output_dir / "body.obj", vertices[0], faces)
    np.savez_compressed(
        args.output_dir / "body_params.npz",
        betas=betas,
        betas10=betas[:10],
        betas10_initial=initial_betas10,
        betas_refined=body_shape,
        full_pose=pose[0],
        transl=transl[0],
        joints=joints[0],
        vertices=vertices[0],
        faces=faces,
        gender=np.asarray(gender),
    )
    if motion_template is not None:
        save_motion(
            motion_template,
            args.output_dir / "motion.npz",
            betas=betas,
            gender=gender,
        )
    render_warning = None
    blender = dynamic_root / "blender-3.6.14-linux-x64" / "blender"
    preview = args.output_dir / "body_preview.png"
    if blender.is_file():
        render = subprocess.run(
            [
                str(blender),
                "--background",
                "--python",
                str(Path(__file__).with_name("render_body.py")),
                "--",
                str(args.output_dir / "body.obj"),
                str(preview),
            ],
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
        )
        if render.returncode or not preview.is_file():
            render_warning = (
                render.stderr.strip()
                or render.stdout.strip()
                or "Blender preview render failed"
            )[-2000:]
    else:
        render_warning = f"Blender executable is missing: {blender}"
    (args.output_dir / "request.json").write_text(
        json.dumps(request, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    output_files = {
        "registered_params": "registered_params.pkl",
        "mesh": "body.obj",
        "parameters": "body_params.npz",
        "request": "request.json",
    }
    if motion_template is not None:
        output_files["motion"] = "motion.npz"
    if preview.is_file():
        output_files["preview"] = "body_preview.png"
    manifest = {
        "status": "complete",
        "gender": gender,
        "semantic_profile": request.get("semantic_profile"),
        "action": {
            "id": action_id,
            "label_zh": action["label_zh"],
            "kind": action["kind"],
            "enabled": motion_template is not None,
        },
        "method": method,
        "runtime": {
            "smplx_device": str(device),
            "gpu_name": (
                torch.cuda.get_device_name(device)
                if device.type == "cuda"
                else None
            ),
        },
        "model_path": str(model_path),
        "topology": {
            "vertices": int(vertices.shape[1]),
            "faces": int(faces.shape[0]),
            "joints": int(joints.shape[1]),
        },
        "files": output_files,
        "notes": [
            "SHAPY returns 10 betas; measurement refinement may populate betas 11-30 and betas 31-300 stay zero.",
            "The 10 official SHAPY betas are frozen; virtual-measurement correction uses SMPL-X betas 11-30.",
            "Static registration reuses the validated project garment-registration pose.",
            "When enabled, motion keeps the selected action sequence and replaces body betas and gender.",
            "A_smplx is intentionally omitted because it is shape-dependent and unused by the current runner.",
        ],
    }
    if render_warning:
        manifest["warnings"] = [render_warning]
    (args.output_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(manifest, ensure_ascii=False))


if __name__ == "__main__":
    main()
